export const DEMO_FLAG = true;

export const demoClusters = [
  {
    _id: 'cl_heavy_streamer',
    clusterLabel: 0,
    personaName: 'Heavy-Data Streamer',
    description:
      'Streams video and music constantly, burns through data fast, rarely calls, barely texts.',
    customerCount: 4210,
    centroid: [0.86, 0.18, 0.12, 0.22, 0.15],
    traits: { data: 'Very High', calling: 'Low', sms: 'Low', roaming: 'Low' },
    color: '#22d3ee',
  },
  {
    _id: 'cl_talk_first',
    clusterLabel: 1,
    personaName: 'Talk-First Connector',
    description: 'Lives on voice calls for work and family, modest data use, low roaming.',
    customerCount: 3120,
    centroid: [0.22, 0.88, 0.3, 0.12, 0.1],
    traits: { data: 'Low', calling: 'Very High', sms: 'Medium', roaming: 'Low' },
    color: '#34d399',
  },
  {
    _id: 'cl_global_roamer',
    clusterLabel: 2,
    personaName: 'Global Roamer',
    description: 'Frequently travels abroad, needs reliable roaming and international minutes.',
    customerCount: 980,
    centroid: [0.5, 0.45, 0.2, 0.92, 0.8],
    traits: { data: 'Medium', calling: 'Medium', sms: 'Low', roaming: 'Very High' },
    color: '#fbbf24',
  },
  {
    _id: 'cl_balanced',
    clusterLabel: 3,
    personaName: 'Balanced Everyday User',
    description: 'Steady, moderate use across data, calls and texts — nothing extreme.',
    customerCount: 5460,
    centroid: [0.45, 0.42, 0.4, 0.18, 0.14],
    traits: { data: 'Medium', calling: 'Medium', sms: 'Medium', roaming: 'Low' },
    color: '#60a5fa',
  },
  {
    _id: 'cl_budget_light',
    clusterLabel: 4,
    personaName: 'Budget-Conscious Light User',
    description: 'Minimal usage across the board, highly price sensitive.',
    customerCount: 2870,
    centroid: [0.12, 0.15, 0.18, 0.05, 0.04],
    traits: { data: 'Low', calling: 'Low', sms: 'Low', roaming: 'Very Low' },
    color: '#a78bfa',
  },
];

export const demoOperators = [
  { id: 'teleplan', name: 'TelePlan', color: '#0077FF' },
];

export const demoPlans = [
  {
    _id: 'P01',
    planName: 'Essential Voice',
    operator: 'teleplan',
    clusterIds: ['cl_budget_light'],
    price: 199,
    dataGB: 5,
    callMinutes: 3000,
    sms: 100,
    roamingIncluded: true,
    validityDays: 28,
    benefits: ['5GB total data', 'Unlimited calls', '100 SMS/day', 'Domestic roaming included'],
    sourceOperatorRef: 'Essential Voice',
  },
  {
    _id: 'P02',
    planName: 'Essential Data',
    operator: 'teleplan',
    clusterIds: ['cl_budget_light', 'cl_balanced'],
    price: 249,
    dataGB: 42,
    callMinutes: 3000,
    sms: 100,
    roamingIncluded: true,
    validityDays: 28,
    benefits: ['1.5GB/day high speed data', 'Unlimited calls', '100 SMS/day', 'Weekend data rollover'],
    sourceOperatorRef: 'Essential Data',
  },
  {
    _id: 'P03',
    planName: 'Student Power',
    operator: 'teleplan',
    clusterIds: ['cl_heavy_streamer', 'cl_balanced'],
    price: 299,
    dataGB: 56,
    callMinutes: 3000,
    sms: 100,
    roamingIncluded: true,
    validityDays: 28,
    benefits: ['2GB/day data + 25GB Edu Pool', 'Unlimited 5G for eligible users', 'Weekend data rollover', 'Cloud/Learning access'],
    sourceOperatorRef: 'Student Power',
  },
  {
    _id: 'P06',
    planName: '5G Freedom',
    operator: 'teleplan',
    clusterIds: ['cl_heavy_streamer'],
    price: 349,
    dataGB: 56,
    callMinutes: 3000,
    sms: 100,
    roamingIncluded: true,
    validityDays: 28,
    benefits: ['Unlimited 5G Data (uncapped)', '2GB/day 4G base quota', 'Unlimited calls', 'Weekend rollover'],
    sourceOperatorRef: '5G Freedom',
  },
  {
    _id: 'P07',
    planName: 'Infinity 4G/5G',
    operator: 'teleplan',
    clusterIds: ['cl_heavy_streamer', 'cl_global_roamer'],
    price: 399,
    dataGB: 100,
    callMinutes: 3000,
    sms: 100,
    roamingIncluded: true,
    validityDays: 28,
    benefits: ['Unlimited 4G/5G Data', 'Unlimited calls nationwide', '100 SMS/day', 'Domestic roaming'],
    sourceOperatorRef: 'Infinity 4G/5G',
  },
  {
    _id: 'P17',
    planName: 'AI & Coding Pro',
    operator: 'teleplan',
    clusterIds: ['cl_heavy_streamer'],
    price: 499,
    dataGB: 100,
    callMinutes: 3000,
    sms: 100,
    roamingIncluded: true,
    validityDays: 28,
    benefits: ['Unlimited 4G/5G Data', '100GB Cloud Storage', 'AI Tool Subscriptions & Credits', 'Dev Platform Benefits'],
    sourceOperatorRef: 'AI & Coding Pro',
  },
  {
    _id: 'P20',
    planName: 'Traveller Pro',
    operator: 'teleplan',
    clusterIds: ['cl_global_roamer'],
    price: 699,
    dataGB: 112,
    callMinutes: 3000,
    sms: 100,
    roamingIncluded: true,
    validityDays: 56,
    benefits: ['2GB/day + Unlimited 5G', '250 ISD Minutes Included', 'Travel Assistance & Partner Benefits', '56 Days Validity'],
    sourceOperatorRef: 'Traveller Pro',
  },
];

export const demoCustomer = {
  _id: 'cust_demo_01',
  name: 'Aarav Mehta',
  phone: '+91 98xxxxxx21',
  tenureMonths: 18,
  contractType: 'postpaid',
  usage: {
    avgCallMin: 420,
    dataGB: 34,
    smsCount: 65,
    dayEveningNightSplit: { day: 0.5, evening: 0.35, night: 0.15 },
    roamingUsage: 2,
    internationalUsage: 0,
  },
  clusterId: 'cl_balanced',
  currentPlanId: 'P02',
  monthlySpend: 449,
  createdAt: '2024-11-02T10:00:00.000Z',
};

export const demoRecommendationHistory = [
  {
    _id: 'rec_1',
    generatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    source: 'chat_profile',
    recommendedPlans: [
      { planId: 'P02', score: 0.89 },
      { planId: 'P03', score: 0.84 },
      { planId: 'P06', score: 0.96 },
      { planId: 'P17', score: 0.92 },
    ],
  },
];

export const demoAdminStats = {
  totalCustomers: 16640,
  totalPlans: demoPlans.length,
  totalClusters: demoClusters.length,
  recommendationsGenerated30d: 8420,
  avgMatchScore: 88,
  lastClusteringRun: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
  lastBatchJobStatus: 'success',
};

export const demoKnowledgeSnippets = [
  { operatorName: 'TelePlan', planName: 'Essential Voice', note: 'Reference 4G budget plan' },
  { operatorName: 'TelePlan', planName: '5G Freedom', note: 'Reference 5G unlimited plan' },
];
